name: Callee Workflow

on:
  workflow_call:
    inputs:
      username:
        description: 'Enter your username'
        required: true
        type: string
    
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello ${{ inputs.username }}"
